spring:
  application:
    name: compraoq
  datasource:
    url: jdbc:postgresql://192.168.1.4:5432/compraoq
    userName: postgres
    password: abc1234
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    table: tb_versions
    schemas: compraoq
