CREATE TABLE COMPRAOQ.ITEM(
    ID         BIGINT       DEFAULT NEXTVAL('COMPRAOQ.SEQ_ITEM'),
    DESCRICAO  VARCHAR(250) ,
    LISTA	   SMALLINT	    ,
    QUANTIDADE SMALLINT     ,
    
    CONSTRAINT PK$ITEM PRIMARY KEY(ID)
);