CREATE TABLE COMPRAOQ.USUARIO(
    ID                 BIGINT       DEFAULT NEXTVAL('COMPRAOQ.SEQ_USUARIO'),
    LOGIN              VARCHAR(255) ,
    NOME_COMPLETO      VARCHAR(255) NOT NULL    ,
    PASSWORD           VARCHAR(255) ,
    HABILITADO         DATE         ,

    CONSTRAINT PK$USUARIO       PRIMARY KEY(ID) ,
    CONSTRAINT UK$USUARIO$LOGIN UNIQUE(LOGIN)
);