CREATE SEQUENCE COMPRAOQ.SEQ_USUARIO
START WITH 1 INCREMENT BY 1;

CREATE TABLE COMPRAOQ.USUARIO(
    ID                 BIGINT       DEFAULT NEXTVAL('COMPRAOQ.SEQ_USUARIO'),
    LOGIN              VARCHAR(255) ,
    NOME_COMPLETO      VARCHAR(255) NOT NULL    ,
    PASSWORD           VARCHAR(255) ,
    CONTA_ATIVA        BIT(1)       DEFAULT B'1',
    CONTA_DESBLOQUEADA BIT(1)       DEFAULT B'1',
    CREDENCIAL_ATIVA   BIT(1)       DEFAULT B'1',
    HABILITADO         BIT(1)       DEFAULT B'1',

    CONSTRAINT PK$USUARIO       PRIMARY KEY(ID),
    CONSTRAINT UK$USUARIO$LOGIN UNIQUE(LOGIN)
);