CREATE TABLE COMPRAOQ.USUARIO_PERMISSAO(
    PERMISSAO_ID BIGINT,
    USUARIO_ID   BIGINT,

    CONSTRAINT PK$USUARIO_PERMISSAO           PRIMARY KEY(PERMISSAO_ID,USUARIO_ID),
    CONSTRAINT FK$PERMISSAO$USUARIO_PERMISSAO FOREIGN KEY(PERMISSAO_ID) REFERENCES COMPRAOQ.PERMISSAO(ID),
    CONSTRAINT FK$USUARIO$USUARIO_PERMISSAO   FOREIGN KEY(USUARIO_ID)   REFERENCES COMPRAOQ.USUARIO(ID)
);